DROP TABLE IF EXISTS sales;
CREATE TABLE sales (
	PRODUCT_ID INT PRIMARY KEY,
	QUANTITY INT,
	PRICE INT
);


INSERT INTO sales VALUES (1, 10, 5);
INSERT INTO sales VALUES (2, 20, 4);

SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

begin;

select PRODUCT_ID, QUANTITY*PRICE from sales;

select sum(QUANTITY*PRICE)from sales;